### ISSUE TITLE
Colocar dados básicos no GIT

### ISSUE THREAD

**Issue by joepreludian** [roquitski/Hello-world#1]
Miss @roquitski; O objetivo da primeira missão é fazer com que você adicione arquivos dentro do seu primeiro repositório. Pra isso quero que você utilize o GIT;

Esse seu repositório servirá como ponto de entrada para o seus estudos. Quero que ele seja sua agenda pessoal sobre o progresso do seus estudos e quero que o utilize para adicionar todos os links, informações úteis e quaisquer coisas relevantes para seu estudo.

## Missão
Vou descrever os passos da missão:
- [x] Criar Repositório;
- [x] Criar três arquivos (README.md) (what_to_learn.md) e (resources.md)
- [x] Colocar um conteúdo simples e realizar o *fluxo padrão do git*.

" Fazer isso sempre para cada adição de informação"

## Fluxo padrão do GIT
Basicamente você precisa fazer o seguinte para adicionar adicionar as coisas pelo GIT:

1. Criar, alterar arquivos, etc;
2. Adicionar os arquivos no git (staging);
3. Realizar o commit das alteraões;
4. Fazer push das alterações para seu servidor;

## Dícas úteis
No link http://rogerdudler.github.io/git-guide/ busque por:
* Workflow;
* Add & commit;
* Pushing changes;

Ao término quero que você me explique como foi que você fez.

**Comment by roquitski** [comment]
Pronto Sir Trigueiro! Ready for the next Challenge ^^ @joepreludian
