### ISSUE TITLE
Setup of development environment - Python

### ISSUE THREAD

**Issue by joepreludian** [roquitski/Hello-world#2]
Você precisa instalar uma ferramenta em seu sistema operacional para poder trabalhar com todo tipo de scripts que pegar pela frente.
Inicialmente quero que você instale o Python no seu sistema operacional. Isso inclui instalar duas coisas

- [x] Instalar Pyenv
- [x] Instalar Pipenv
(Nessa ordem)

Segue a documentação dos projetos:
* https://github.com/pyenv/pyenv
* https://github.com/pypa/pipenv

Antes de instalar os dois você precisa fazer uma instalação de alguns modulos no seu sistema operacional. Segue uma dica: Você precisa instalar um grupo de aplicações.

    $ sudo dnf grouplist; 

Lista os grupos disponíveis. Como você vai precisar compilar módulos vc precisa instalar um Grupo chamado *Development Tools*.

    $ sudo dnf groupinstall <nome do grupo>

### Dicas
Se vc usar um comando que precisa de argumentos que levem espaço, por exemplo:
* argumento_1;
* argumento_2;
*um terceiro argumento que leva espaço;

O comando ficaria assim:

    $ comando argumento_1 argumento_2 "um terceiro argumento que leva espaço"

Caso não seja "escapado" entre áspas, o comando teria os seguintes argumentos:
* argumento_1;
* argumento_2;
* um;
* terceiro;
* argumento;
* que;
* leva;
* espaço;

Good luck ;)

**Comment by roquitski** [comment]
@joepreludian done
